from src.RestaurantRatingPrediction.components.data_ingestion import DataIngestion
from src.RestaurantRatingPrediction.components.data_transformation import DataTransformation

import os
import sys
from src.RestaurantRatingPrediction.logger import logging
from src.RestaurantRatingPrediction.exception import customexception
import pandas as pd

obj=DataIngestion()
train_data_path,test_data_path=obj.initiate_data_ingestion()

data_transformation=DataTransformation()
train_arr,test_arr=data_transformation.initialize_data_transformation(train_data_path,test_data_path)